// Mocks generated by Mockito 5.3.2 from annotations
// in money_manager/test/features/home/domain/usecases/get_month_transaction_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:money_manager/core/error/failures.dart' as _i5;
import 'package:money_manager/features/transaction/data/models/transaction_add_model.dart'
    as _i6;
import 'package:money_manager/features/transaction/data/models/transaction_model.dart'
    as _i7;
import 'package:money_manager/features/transaction/domain/repositories/transaction_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i3.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> addTransaction(
          _i6.TransactionAddModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTransaction,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #addTransaction,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> updateTransaction(
          _i7.TransactionModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #updateTransaction,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> deleteTransaction(
          _i7.TransactionModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #deleteTransaction,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}
